on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
